using System;
using System.IO;
using System.Text.RegularExpressions;

namespace TsdLib.Configuration
{
    public interface IRemiConfigAccess
    {
        void WriteConfigStringToRemi(string data, string applicationName, string applicationVersion, string configType);
        string ReadConfigStringFromRemi(string applicationName, string applicationVersion, string configType);
    }

    public class RemiConfigAccessTest : IRemiConfigAccess
    {
        private const string AppVersionFilter = @"\d+\.\d+";
        private readonly string _settingsBasePath;

        public RemiConfigAccessTest(string settingsBasePath)
        {
            _settingsBasePath = settingsBasePath;
        }

        public void WriteConfigStringToRemi(string data, string applicationName, string applicationVersion, string configType)
        {
            Match match = Regex.Match(applicationVersion, AppVersionFilter);
            string appVersion = match.Success ? match.Value : applicationVersion;
            string directoryName = Path.Combine(_settingsBasePath, applicationName, appVersion, configType);
            if (!Directory.Exists(directoryName))
                Directory.CreateDirectory(directoryName);

            string fileName = Path.Combine(directoryName, "config.xml");

            File.WriteAllText(fileName, data);
        }

        public string ReadConfigStringFromRemi(string applicationName, string applicationVersion, string configType)
        {
            Match match = Regex.Match(applicationVersion, AppVersionFilter);
            string appVersion = match.Success ? match.Value : applicationVersion;
            string fileName = Path.Combine(_settingsBasePath, applicationName, appVersion, configType, "config.xml");

            if (!File.Exists(fileName))
                throw new ConfigDoesNotExistInRemiException(applicationName, applicationVersion, configType);

            string data = File.ReadAllText(fileName);

            return data;
        }
    }

    /// <summary>
    /// Will be replaced with the exception generated by RemiControl
    /// </summary>
    class ConfigDoesNotExistInRemiException : Exception
    {
        public string ApplicationName { get; private set; }
        public string ApplicationVersion { get; private set; }
        public string ConfigType { get; private set; }

        public override string Message
        {
            get { return ConfigType + " does not exist for " + ApplicationName + " v." + ApplicationVersion + "."; }
        }

        public ConfigDoesNotExistInRemiException(string applicationName, string applicationVersion, string configType)
        {
            ApplicationName = applicationName;
            ApplicationVersion = applicationVersion;
            ConfigType = configType;
        }
    }
}