using System;
using System.IO;
using System.Text.RegularExpressions;

namespace TsdLib.Configuration
{
    /// <summary>
    /// A simulated RemiControl implementation that persists Remi settings to the local disk.
    /// </summary>
    public class RemiControlTest : IRemiControl
    {
        private const string AppVersionFilter = @"\d+\.\d+";
        private readonly string _settingsBasePath;

        /// <summary>
        /// Initialize a new RemiControlTest instance specifying a location on the local disk to persist settings.
        /// </summary>
        /// <param name="settingsBasePath">Absolute path on the local file system to use for persisting settings.</param>
        public RemiControlTest(string settingsBasePath)
        {
            _settingsBasePath = settingsBasePath;
        }

        /// <summary>
        /// Write a string to the database using the name/version of the test system and dataDescription as indexes.
        /// </summary>
        /// <param name="data">Data to write.</param>
        /// <param name="testSystemName">Name of the test system.</param>
        /// <param name="testSystemVersion">Version of the test system.</param>
        /// <param name="dataDescription">Description of the data</param>
        public void WriteStringToRemi(string data, string testSystemName, string testSystemVersion, string dataDescription)
        {
            Match match = Regex.Match(testSystemVersion, AppVersionFilter);
            string appVersion = match.Success ? match.Value : testSystemVersion;
            string directoryName = Path.Combine(_settingsBasePath, testSystemName, appVersion);
            if (!Directory.Exists(directoryName))
                Directory.CreateDirectory(directoryName);

            File.WriteAllText(Path.Combine(directoryName, dataDescription), data);
        }

        /// <summary>
        /// Read a string from the database using the name/version of the test system and dataDescription as indexes.
        /// </summary>
        /// <param name="testSystemName">Name of the test system.</param>
        /// <param name="testSystemVersion">Version of the test system.</param>
        /// <param name="dataDescription">Description of the data</param>
        /// <returns>Data read from Remi in the specified indexes.</returns>
        public string ReadStringFromRemi(string testSystemName, string testSystemVersion, string dataDescription)
        {
            Match match = Regex.Match(testSystemVersion, AppVersionFilter);
            string appVersion = match.Success ? match.Value : testSystemVersion;
            string filePath = Path.Combine(_settingsBasePath, testSystemName, appVersion, dataDescription);

            if (!File.Exists(filePath))
                throw new ConfigDoesNotExistInRemiException(testSystemName, testSystemVersion, dataDescription);

            string data = File.ReadAllText(filePath);

            return data;
        }
    }

    /// <summary>
    /// Will be replaced with the exception generated by RemiControl
    /// </summary>
    [Serializable]
    class ConfigDoesNotExistInRemiException : Exception
    {
        public ConfigDoesNotExistInRemiException(string testSystemName, string testSystemVersion, string configType)
            : base(configType + " does not exist for " + testSystemName + " v." + testSystemVersion + ".") { }
    }
}