//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.Instruments
{
    using System;
    using TsdLib.Instrument;
    using TsdLib.Instrument.Dummy;
    using TsdLib.Instrument.Telnet;
    
    
    // ReSharper disable once FieldCanBeMadeReadOnly.Local
    [IdQuery("BlackBerry Device")]
    [CommandDelay("200")]
    public class BlackBerry : InstrumentBase<TelnetConnection>
    {
        
        static TelnetFactory _factory = new TelnetFactory();
        
        internal BlackBerry(TelnetConnection connection) : 
                base(connection)
        {
        }
        
        internal BlackBerry(DummyConnection connection) : 
                base(connection)
        {
        }
        
        protected override string ModelNumberMessage
        {
            get
            {
                return "cat /pps/services/hw_info/inventory | grep Board_Type::";
            }
        }
        
        protected override string ModelNumberRegEx
        {
            get
            {
                return "(?<=Board_Type::).*";
            }
        }
        
        protected override string SerialNumberMessage
        {
            get
            {
                return "cat /pps/system/nvram/deviceinfo | grep BSN::";
            }
        }
        
        protected override string SerialNumberRegEx
        {
            get
            {
                return "(?<=BSN::).*";
            }
        }
        
        protected override string FirmwareVersionMessage
        {
            get
            {
                return "cat /pps/services/deviceproperties | grep scmbundle::";
            }
        }
        
        protected override string FirmwareVersionRegEx
        {
            get
            {
                return "(?<=scmbundle::).*";
            }
        }
        
        public static BlackBerry Connect()
        {
            return _factory.GetInstrument<BlackBerry>();
        }
        
        public static BlackBerry Connect(string address)
        {
            return _factory.GetInstrument<BlackBerry>(address);
        }
        
        public static BlackBerry Connect(ConnectionBase connection)
        {
            return _factory.GetInstrument<BlackBerry>(((TelnetConnection)(connection)));
        }
        
        public virtual String GetImei()
        {
            System.Threading.Monitor.Enter(Connection.SyncRoot);
            try
            {
                Connection.SendCommand("cat /pps/system/nvram/deviceinfo | grep IMEI::", -1);
                return Connection.GetResponse<String>("(?<=IMEI::).*(?=\\r\\nInProduction)");
            }
            finally
            {
                System.Threading.Monitor.Exit(Connection.SyncRoot);
            }
        }
        
        public virtual String GetChipsetFamily()
        {
            System.Threading.Monitor.Enter(Connection.SyncRoot);
            try
            {
                Connection.SendCommand("wl_bcm_dhd revinfo | grep chipnum", -1);
                return Connection.GetResponse<String>("(?<=chipnum 0x)\\d+");
            }
            finally
            {
                System.Threading.Monitor.Exit(Connection.SyncRoot);
            }
        }
    }
}
