//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.Instruments
{
    using System;
    using TsdLib.Instrument;
    using TsdLib.Instrument.Dummy;
    
    
    // ReSharper disable once FieldCanBeMadeReadOnly.Local
    [IdQuery("MyInstrument, Model 12345")]
    public class DummyPowerSupply : InstrumentBase<DummyConnection>
    {
        
        static DummyFactory _factory = new DummyFactory();
        
        internal DummyPowerSupply(DummyConnection connection) : 
                base(connection)
        {
        }
        
        public virtual DummyConnection DummyConnection
        {
            get
            {
                return Connection;
            }
        }
        
        protected override string ModelNumberMessage
        {
            get
            {
                return "*IDN?";
            }
        }
        
        protected override string SerialNumberMessage
        {
            get
            {
                return "*IDN?";
            }
        }
        
        protected override string FirmwareVersionMessage
        {
            get
            {
                return "*IDN?";
            }
        }
        
        public static DummyPowerSupply Connect()
        {
            return _factory.GetInstrument<DummyPowerSupply>();
        }
        
        public static DummyPowerSupply Connect(string address)
        {
            return _factory.GetInstrument<DummyPowerSupply>(address);
        }
        
        public void SetVoltage(Double voltage)
        {
            Connection.SendCommand("SET:VOLT {0}", -1, voltage);
        }
        
        public Double GetCurrent()
        {
            Connection.SendCommand("GET:CURRENT?", -1);
            return Connection.GetResponse<Double>();
        }
    }
    
    // ReSharper disable once FieldCanBeMadeReadOnly.Local
    [IdQuery("MyInstrument, Model 12345")]
    public class DummyPowerSupply2 : InstrumentBase<DummyConnection>
    {
        
        static DummyFactory _factory = new DummyFactory();
        
        internal DummyPowerSupply2(DummyConnection connection) : 
                base(connection)
        {
        }
        
        public virtual DummyConnection DummyConnection
        {
            get
            {
                return Connection;
            }
        }
        
        protected override string ModelNumberMessage
        {
            get
            {
                return "*IDN?";
            }
        }
        
        protected override string SerialNumberMessage
        {
            get
            {
                return "*IDN?";
            }
        }
        
        protected override string FirmwareVersionMessage
        {
            get
            {
                return "*IDN?";
            }
        }
        
        public static DummyPowerSupply2 Connect()
        {
            return _factory.GetInstrument<DummyPowerSupply2>();
        }
        
        public static DummyPowerSupply2 Connect(string address)
        {
            return _factory.GetInstrument<DummyPowerSupply2>(address);
        }
        
        public void SetVoltage(Double voltage)
        {
            Connection.SendCommand("SET:VOLT {0}", -1, voltage);
        }
        
        public Double GetCurrent()
        {
            Connection.SendCommand("GET:CURRENT?", -1);
            return Connection.GetResponse<Double>();
        }
    }
}
